[project]
name = "idm-activator"
version = "1.0.3"
description = "Free & Safe IDM Activator"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pyinstaller>=6.20.0",
    "pyqt6>=6.11.0",
    "taskipy>=1.14.1",
]
[tool.taskipy.tasks]
build = "pyinstaller src/app.py --onefile --icon src/assets/icon.ico --noconsole"
